### PR TITLE
Fix terminal exit command

### PR DESCRIPTION
**Pull request by ashblue**
Exit command on a terminal now works as expected. Also cleans up several brittle tests with DRY consolidation.

https://user-images.githubusercontent.com/643307/217355532-f3a0831e-3bfb-4386-8101-52a958e6a5e8.mov

### CODE REVIEW

**Review by rikasun — APPROVED** [review]
👍🏼👍🏼👍🏼

**Comment by jnewland** [comment]
https://linear.app/cased/issue/CAS-457#comment-b82e2310 has some notes on one other bit of behavior we'd like to retain if possible.

**Review by tnm — APPROVED** [review]

**Comment by ashblue** [comment]
@jnewland assuming it's fine to merge what I have here and handle that as a separate ticket? I think that might require a chunk of refactoring to get it working.

**Comment by jnewland** [comment]
@ashblue yes totally! Just wanted to make sure it was being tracked.

**Comment by ashblue** [comment]
Almost forgot to link the split ticket here. Adding for posterity https://linear.app/cased/issue/CAS-462/terminal-should-stay-open-when-exited-with-a-special-flag

**Pull request merged**
