### PR TITLE
Terminal crash on cat no longer crashes the entire session

### PR DESCRIPTION
**Pull request by ashblue**
So I've tried everything I can think of to gracefully handle the cat error on the front-end. But for some odd reason xterm's try catch can't handle the cat response. Nor does it have an error interception tool to detect the error. That said I think I've come up with a fix that works for now.

https://user-images.githubusercontent.com/643307/223878894-78717902-1ec1-4e2a-bfdc-66dd2425c5ac.mov

The above solution still spits out errors to the console. But it does stop the page from crashing and keeps the console going just fine. I wish we could gracefully handle this crash but I can't seem to find a solution to do so. Apparently, there are some plugins that could potentially help (Xterm authors mentioned it in a few Git issues). But I think those libs are deprecated as of XTerm.js v5.

I found some GitHub issues mentioning Xterm's `onBinary` event which might actually fix this situation. But there is little to no documentation on how to use it https://github.com/xtermjs/xterm.js/pull/2566

### CODE REVIEW

**Review by rikasun — APPROVED** [review]
👍🏼👍🏼👍🏼

**Comment by jnewland** [comment]
Nice interim fix! It'd be rad to be able to show the user something in this situation. It's also a bit surprising that Bash tried to execute some of the output it looks like?

Random question after observing the exceptions logged in the console, which are from `LogService.ts`: does setting xterm.js's LogLevel to `off` help the situation possibly? Can we do without whatever it logs?

https://github.com/xtermjs/xterm.js/blob/4037b943b9d9b2b44ef9ab96dd09b42363c96c93/typings/xterm.d.ts#L21

**Comment by ashblue** [comment]
> Nice interim fix! It'd be rad to be able to show the user something in this situation. It's also a bit surprising that Bash tried to execute some of the output it looks like?

Yeah Xterm is trying to execute the returned details from the server. It doesn't seem like there is a way to catch or detect that the code will error. As the Xterm write output seems to be offloaded to a separate event stream / thread.

> Random question after observing the exceptions logged in the console, which are from `LogService.ts`: does setting xterm.js's LogLevel to `off` help the situation possibly? Can we do without whatever it logs?
> 
> https://github.com/xtermjs/xterm.js/blob/4037b943b9d9b2b44ef9ab96dd09b42363c96c93/typings/xterm.d.ts#L21

Pretty sure if we set the LogLevel to off it would stop logging everything. That could help if we could intercept / catch the error. But there doesn't seem to be a way to do so. I'm wondering if there is a way to run a command that will test if Xterm.js can interpret the string or not without erroring. If we could do that we could detect that a string parse is going to fail. I think I'd have to dig through the source on the write command and see what specific line of logic fails https://github.com/xtermjs/xterm.js/blob/4037b943b9d9b2b44ef9ab96dd09b42363c96c93/typings/xterm.d.ts#L1062. That `Parsing Error:` in the source will probably tell us how to test a line before we try and write it.

**Comment by jnewland** [comment]
> Pretty sure if we set the LogLevel to off it would stop logging everything. 

My read of the source it would stop attempting to log the "parsing error" and thus stop crashing while retaining all other existing functionality:

https://github.com/xtermjs/xterm.js/blob/4037b943b9d9b2b44ef9ab96dd09b42363c96c93/src/common/services/LogService.ts
https://github.com/xtermjs/xterm.js/blob/4037b943b9d9b2b44ef9ab96dd09b42363c96c93/src/common/InputHandler.ts#L374

**Comment by ashblue** [comment]
Hmmmm, that might mask other errors I'd suspect though 🤔 That input handler source might have a solution in it. Ideally as soon as we hit a breaking write I'd like to abort the remaining lines of the command and display a concise error message.

**Pull request merged**
